# Generated by Django 4.1.10 on 2023-07-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type_control',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
