# Generated by Django 4.1.10 on 2023-07-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_type_control'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='type_control',
            new_name='tipi_nedir',
        ),
    ]
